services:
  mysql:
    image: mysql:8.0
    container_name: ecomarket_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sistema_ventas
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3308:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db/db/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    networks:
      - ecomarket_network
    healthcheck:
      # Este comando intenta hacer un SELECT real a la tabla del sistema
      test: ["CMD-SHELL", "mysql -u root -proot -e 'SELECT 1;'"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 30s

  db:
    build: ./db/db
    container_name: ecomarket_db
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/sistema_ventas?createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    networks:
      - ecomarket_network

  frontend:
    build: ./frontend/frontend
    container_name: ecomarket_frontend
    ports:
      - "8081:8081"
    depends_on:
      - db
    networks:
      - ecomarket_network

  sistemareportes:
    build: ./sistemareportes
    container_name: ecomarket_sistemareportes
    ports:
      - "8082:8082"
    depends_on:
      - db
    networks:
      - ecomarket_network

volumes:
  mysql_data:

networks:
  ecomarket_network:
    driver: bridge