spring.application.name=db

spring.datasource.url=jdbc:mysql://localhost:3308/sistema_ventas?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true