spring.application.name=pedidos360-reportes
server.port=8082
pedidos360.reportes.internal-key=${PEDIDOS360_REPORTES_INTERNAL_KEY:pedidos360-internal}

APP.SECURITY.AUDIENCE.CLIENT-ID="64533da2-6952-4e6c-8afa-c4eafddd0060"
APP.SECURITY.AUDIENCE.API-URI="je"